version: '3'

services:
    db:
        env_file: ./.env
        container_name: mysite-db
        image: postgres:13.3
        restart: on-failure
        environment:
          POSTGRES_DB: ${DB_NAME}
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PS}
          POSTGRES_ALLOW_EMPTY_PASSWORD: "no"
        volumes:
          - postgresql:/var/lib/postgresql/data
        ports:
          - 5432:5432
    nginx: 
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            - static_volume:/usr/share/nginx/html/static
            - media_volume:/app/backend/media
            - ./docker/nginx/production:/etc/nginx/conf.d
            - ./docker/nginx/certbot/conf:/etc/letsencrypt
            - ./docker/nginx/certbot/www:/var/www/certbot
        depends_on: 
            - backend
    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./docker/nginx/certbot/conf:/etc/letsencrypt
            - ./docker/nginx/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'" 
    backend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        volumes:
            
        entrypoint: /app/docker/backend/wsgi-entrypoint.sh
        volumes:
            - static_volume:/usr/share/nginx/html/static
            - media_volume:/app/backend/media
        expose:
            - 8000        

volumes:
    postgresql: {}
    static_volume: {}
    media_volume: {}